http:
  port: "8081"

cryptoranking:
  host: api.coinranking.com
  version: /v2
  #host: coinranking1.p.rapidapi.com
  port: "443"
  
amqp:
  host: "localhost"
  port: "5672"
  username: "Dmytro"
  password: "![q8lREinYj9AQON6OZfw3Yg==]"
  
mongodb:
  database: "cryptocurrencies_task"
  
smtp:
  host: "smtp.gmail.com"
  port: "587"
  user: "your@mail.com"
  password: "your_pass"
  
viber_request:
  host: "chatapi.viber.com"
  basePath: "/pa"
  port: "443"
  token: "your_viber_token"

telegram_request:
  host: "api.telegram.org"
  port: "443"
  basePath: "/bot"
  token: "your_telegram_token"
  